# Generated by Django 5.2.4 on 2025-07-27 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='data_inclusao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
